name: "Cronjob ThuVienPhapLuat"
on:
  workflow_run:
    workflows: ["Cronjob VnExpress"]
    types: [in_progress]
jobs:
  thuvienphapluat_job:
    name: ThÆ° Viá»‡n PhÃ¡p Luáº­t - ${{ matrix.rand_seed }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - feed_list: "https://thuvienphapluat.vn/rss.xml"
            readme_path: "./docs/index.md"
            rand_seed: "thuvienphapluat"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in ThÆ° Viá»‡n PhÃ¡p Luáº­t news
        uses: ePlus-DEV/blog-post-workflow@v1.0.2
        with:
          retry_count: 5
          readme_path: ${{ matrix.readme_path }}
          feed_list: ${{ matrix.feed_list }}
          committer_email: "h250694@gmail.com"
          commit_message: "Get ThuVienPhapLuat news - ${{ matrix.rand_seed }} - ${{ github.event.repository.updated_at}}"
          rand_seed: ${{ matrix.rand_seed }}
          comment_tag_name: ${{ matrix.rand_seed }}
          date_format: "HH:MM dd/mm/yyyy"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰) [$title]($url) - $date"
          max_post_count: 60
